on:
  pull_request:
  push:
    branches:
      - master
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        run: ./gradlew build
      - name: Test
        run: ./gradlew testDebugUnitTest
      - name: Test Results
        uses: EnricoMi/publish-unit-test-result-action@v1.9
        if: always()
        with:
          files: app/build/test-results/**/*.xml
